# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27a4a22f7213c5c16f0bcbc956a39cf04468cb2d56bbebb5cfc91e78fa08db868336dd8313d3b2eb72abdebeda15bc7fe27a675852c7749e7518bfa2b2a59c9

test:
  secret_key_base: 81be81339d135622b4639bfe8de144e9afca5e14e360fa36b7999746cadb906cebedb75e8ca0ce8609b75b50d064e2b804b57ad34cbff6169aa9b3d3489c4a16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
